// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/interaction/v1/interaction_service.proto

package v1 // import "github.com/census-instrumentation/opencensus-proto/gen-go/agent/interaction/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import interactionproto "github.com/draffensperger/opencensus-web/gen-go/interactionproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportInteractionsRequest struct {
	Interactions         []*interactionproto.Interaction `protobuf:"bytes,1,rep,name=interactions,proto3" json:"interactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ExportInteractionsRequest) Reset()         { *m = ExportInteractionsRequest{} }
func (m *ExportInteractionsRequest) String() string { return proto.CompactTextString(m) }
func (*ExportInteractionsRequest) ProtoMessage()    {}
func (*ExportInteractionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_interaction_service_270cf5e4816e2779, []int{0}
}
func (m *ExportInteractionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportInteractionsRequest.Unmarshal(m, b)
}
func (m *ExportInteractionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportInteractionsRequest.Marshal(b, m, deterministic)
}
func (dst *ExportInteractionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportInteractionsRequest.Merge(dst, src)
}
func (m *ExportInteractionsRequest) XXX_Size() int {
	return xxx_messageInfo_ExportInteractionsRequest.Size(m)
}
func (m *ExportInteractionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportInteractionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportInteractionsRequest proto.InternalMessageInfo

func (m *ExportInteractionsRequest) GetInteractions() []*interactionproto.Interaction {
	if m != nil {
		return m.Interactions
	}
	return nil
}

type ExportInteractionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportInteractionsResponse) Reset()         { *m = ExportInteractionsResponse{} }
func (m *ExportInteractionsResponse) String() string { return proto.CompactTextString(m) }
func (*ExportInteractionsResponse) ProtoMessage()    {}
func (*ExportInteractionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_interaction_service_270cf5e4816e2779, []int{1}
}
func (m *ExportInteractionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportInteractionsResponse.Unmarshal(m, b)
}
func (m *ExportInteractionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportInteractionsResponse.Marshal(b, m, deterministic)
}
func (dst *ExportInteractionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportInteractionsResponse.Merge(dst, src)
}
func (m *ExportInteractionsResponse) XXX_Size() int {
	return xxx_messageInfo_ExportInteractionsResponse.Size(m)
}
func (m *ExportInteractionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportInteractionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportInteractionsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ExportInteractionsRequest)(nil), "opencensus.proto.agent.interaction.v1.ExportInteractionsRequest")
	proto.RegisterType((*ExportInteractionsResponse)(nil), "opencensus.proto.agent.interaction.v1.ExportInteractionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExportClient is the client API for Export service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExportClient interface {
	ExportInteractions(ctx context.Context, in *ExportInteractionsRequest, opts ...grpc.CallOption) (*ExportInteractionsResponse, error)
}

type exportClient struct {
	cc *grpc.ClientConn
}

func NewExportClient(cc *grpc.ClientConn) ExportClient {
	return &exportClient{cc}
}

func (c *exportClient) ExportInteractions(ctx context.Context, in *ExportInteractionsRequest, opts ...grpc.CallOption) (*ExportInteractionsResponse, error) {
	out := new(ExportInteractionsResponse)
	err := c.cc.Invoke(ctx, "/opencensus.proto.agent.interaction.v1.Export/ExportInteractions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportServer is the server API for Export service.
type ExportServer interface {
	ExportInteractions(context.Context, *ExportInteractionsRequest) (*ExportInteractionsResponse, error)
}

func RegisterExportServer(s *grpc.Server, srv ExportServer) {
	s.RegisterService(&_Export_serviceDesc, srv)
}

func _Export_ExportInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServer).ExportInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opencensus.proto.agent.interaction.v1.Export/ExportInteractions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServer).ExportInteractions(ctx, req.(*ExportInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Export_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opencensus.proto.agent.interaction.v1.Export",
	HandlerType: (*ExportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportInteractions",
			Handler:    _Export_ExportInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/interaction/v1/interaction_service.proto",
}

func init() {
	proto.RegisterFile("github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/interaction/v1/interaction_service.proto", fileDescriptor_interaction_service_270cf5e4816e2779)
}

var fileDescriptor_interaction_service_270cf5e4816e2779 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0x0d, 0xc2, 0x15, 0xd1, 0x2a, 0x8d, 0xba, 0x58, 0xc8, 0x82, 0x70, 0x85, 0x97, 0xb0,
	0xe7, 0x0b, 0xe8, 0x81, 0x85, 0x8d, 0x2c, 0x67, 0x67, 0x23, 0x7b, 0x61, 0x58, 0x53, 0xec, 0x64,
	0xcd, 0xcc, 0x2e, 0xbe, 0x88, 0x95, 0xbd, 0xcf, 0x29, 0x6e, 0x84, 0xcb, 0xb1, 0x77, 0x70, 0x78,
	0x65, 0x66, 0xfe, 0xf9, 0xfe, 0x3f, 0xc9, 0xc8, 0xbe, 0x76, 0xfc, 0xd6, 0xad, 0xb4, 0xf5, 0x8d,
	0xb1, 0x80, 0xd4, 0xd1, 0xcc, 0x21, 0x71, 0xe8, 0x1a, 0x40, 0xae, 0xd8, 0x79, 0x34, 0xbe, 0x05,
	0xfc, 0x6b, 0xb5, 0xc1, 0xb3, 0x37, 0x14, 0x6c, 0x52, 0x34, 0xb1, 0x58, 0xd5, 0x80, 0x6c, 0x1c,
	0x32, 0x84, 0xca, 0x0e, 0x73, 0x7d, 0x91, 0x1e, 0x5f, 0x09, 0x42, 0xef, 0x2c, 0xe8, 0x41, 0xae,
	0xae, 0xd7, 0x80, 0x58, 0xd1, 0x03, 0x40, 0x27, 0x13, 0xba, 0x2f, 0xb2, 0x62, 0xe4, 0xb3, 0xdb,
	0x21, 0x72, 0xf2, 0x46, 0x5e, 0x3c, 0x7c, 0xb4, 0x3e, 0xf0, 0xe3, 0xba, 0x45, 0x4b, 0x78, 0xef,
	0x80, 0x58, 0x95, 0xf2, 0x34, 0x99, 0xa0, 0x73, 0x71, 0x75, 0x3c, 0x3d, 0x99, 0xdf, 0xe8, 0x51,
	0x9a, 0xcd, 0x1c, 0x3a, 0x61, 0x2d, 0x37, 0x08, 0xf9, 0xa5, 0xcc, 0xb6, 0xd9, 0x51, 0xeb, 0x91,
	0x60, 0xfe, 0x2d, 0xe4, 0x24, 0xb6, 0xd5, 0x97, 0x90, 0x6a, 0xac, 0x54, 0x77, 0x7a, 0xaf, 0x97,
	0xd0, 0x3b, 0xef, 0x94, 0xdd, 0x1f, 0x40, 0x88, 0x31, 0xf3, 0xa3, 0xc5, 0xa7, 0x90, 0x53, 0xe7,
	0xf7, 0x23, 0x2d, 0xce, 0x12, 0xc8, 0x73, 0xfc, 0xd6, 0xf2, 0x57, 0x5d, 0x8a, 0x97, 0xa7, 0x7f,
	0xec, 0x53, 0x0d, 0x38, 0xab, 0xb7, 0x6f, 0xd0, 0x6a, 0x32, 0x48, 0x6e, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0x4c, 0x3f, 0x8d, 0xa8, 0x02, 0x00, 0x00,
}
