// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/interaction/v1/interaction.proto

package v1 // import "github.com/census-instrumentation/opencensus-proto/gen-go/interaction/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A UI interation represents a measurable user interaction in a user interface
// client (usually a web browser or mobile app). UI actions will be transformed
// into spans and metrics by specialized interceptors in the OpenCensus agent.
//
// Clients will typically communicate with the agent over the open internet,
// and for web clients, the communication with be over HTTP. For web clients
// particularly, it's also important that the amount of client code be small.
// These considerations impact how the fields in this proto are specified.
type Interaction struct {
	TraceId               string                             `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId                string                             `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	WebPerformanceEntries []*Interaction_WebPerformanceEntry `protobuf:"bytes,3,rep,name=web_performance_entries,json=webPerformanceEntries,proto3" json:"web_performance_entries,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                           `json:"-"`
	XXX_unrecognized      []byte                             `json:"-"`
	XXX_sizecache         int32                              `json:"-"`
}

func (m *Interaction) Reset()         { *m = Interaction{} }
func (m *Interaction) String() string { return proto.CompactTextString(m) }
func (*Interaction) ProtoMessage()    {}
func (*Interaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_interaction_b15fda8848a69abd, []int{0}
}
func (m *Interaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction.Unmarshal(m, b)
}
func (m *Interaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction.Marshal(b, m, deterministic)
}
func (dst *Interaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction.Merge(dst, src)
}
func (m *Interaction) XXX_Size() int {
	return xxx_messageInfo_Interaction.Size(m)
}
func (m *Interaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction proto.InternalMessageInfo

func (m *Interaction) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Interaction) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *Interaction) GetWebPerformanceEntries() []*Interaction_WebPerformanceEntry {
	if m != nil {
		return m.WebPerformanceEntries
	}
	return nil
}

// TODO: Parent/child links to enable relationships between a UiAction and
// other UiActions (such as a button click as a child of page navigation).
type Interaction_WebPerformanceEntry struct {
	Attributes           map[string]string `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Interaction_WebPerformanceEntry) Reset()         { *m = Interaction_WebPerformanceEntry{} }
func (m *Interaction_WebPerformanceEntry) String() string { return proto.CompactTextString(m) }
func (*Interaction_WebPerformanceEntry) ProtoMessage()    {}
func (*Interaction_WebPerformanceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_interaction_b15fda8848a69abd, []int{0, 0}
}
func (m *Interaction_WebPerformanceEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_WebPerformanceEntry.Unmarshal(m, b)
}
func (m *Interaction_WebPerformanceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_WebPerformanceEntry.Marshal(b, m, deterministic)
}
func (dst *Interaction_WebPerformanceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_WebPerformanceEntry.Merge(dst, src)
}
func (m *Interaction_WebPerformanceEntry) XXX_Size() int {
	return xxx_messageInfo_Interaction_WebPerformanceEntry.Size(m)
}
func (m *Interaction_WebPerformanceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_WebPerformanceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_WebPerformanceEntry proto.InternalMessageInfo

func (m *Interaction_WebPerformanceEntry) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*Interaction)(nil), "opencensus.proto.interaction.v1.Interaction")
	proto.RegisterType((*Interaction_WebPerformanceEntry)(nil), "opencensus.proto.interaction.v1.Interaction.WebPerformanceEntry")
	proto.RegisterMapType((map[string]string)(nil), "opencensus.proto.interaction.v1.Interaction.WebPerformanceEntry.AttributesEntry")
}

func init() {
	proto.RegisterFile("github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/interaction/v1/interaction.proto", fileDescriptor_interaction_b15fda8848a69abd)
}

var fileDescriptor_interaction_b15fda8848a69abd = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xd9, 0x2e, 0xff, 0xf6, 0xef, 0xf4, 0x60, 0x89, 0x4a, 0x6b, 0x2f, 0x2d, 0x9e, 0x7a,
	0x69, 0x96, 0xea, 0x45, 0x04, 0x41, 0x0b, 0x82, 0xbd, 0x2d, 0xbd, 0x08, 0x5e, 0x4a, 0x76, 0x3b,
	0xb6, 0x41, 0x9b, 0x2c, 0xc9, 0x6c, 0x6b, 0x4f, 0x5e, 0xfc, 0x6c, 0x7e, 0x2e, 0xd9, 0x6c, 0xb1,
	0xa1, 0x8a, 0x82, 0xde, 0xf2, 0xde, 0x9b, 0x99, 0xfc, 0x18, 0x06, 0xe6, 0x33, 0x49, 0xf3, 0x3c,
	0xe1, 0xa9, 0x5e, 0x44, 0x29, 0x2a, 0x9b, 0xdb, 0xbe, 0x54, 0x96, 0x4c, 0xbe, 0x40, 0x45, 0x82,
	0xa4, 0x56, 0x91, 0xce, 0x50, 0x6d, 0xa2, 0xcc, 0x68, 0xd2, 0x91, 0x35, 0xa9, 0x67, 0x46, 0xa5,
	0x29, 0x15, 0xa1, 0x11, 0xa9, 0xeb, 0x58, 0x0e, 0x7c, 0xc9, 0x5d, 0x01, 0xeb, 0x6c, 0x5b, 0x4a,
	0x87, 0xfb, 0x35, 0xcb, 0xc1, 0xc9, 0x6b, 0x08, 0xf5, 0xd1, 0xd6, 0x62, 0xc7, 0xf0, 0x9f, 0x8c,
	0x48, 0x71, 0x22, 0xa7, 0xad, 0xa0, 0x1b, 0xf4, 0xf6, 0xc6, 0x35, 0xa7, 0x47, 0x53, 0xd6, 0x84,
	0x9a, 0xcd, 0x84, 0x2a, 0x92, 0x8a, 0x4b, 0xaa, 0x85, 0x1c, 0x4d, 0xd9, 0x33, 0x34, 0x57, 0x98,
	0x4c, 0x32, 0x34, 0x0f, 0xda, 0x2c, 0x84, 0x4a, 0x71, 0x82, 0x8a, 0x8c, 0x44, 0xdb, 0x0a, 0xbb,
	0x61, 0xaf, 0x7e, 0x7a, 0xc5, 0x7f, 0xc0, 0xe0, 0x1e, 0x02, 0xbf, 0xc3, 0x24, 0xde, 0x8e, 0xba,
	0x51, 0x64, 0xd6, 0xe3, 0xa3, 0xd5, 0x27, 0x53, 0xa2, 0x6d, 0xbf, 0x05, 0x70, 0xf0, 0x45, 0x39,
	0xcb, 0x00, 0x04, 0x91, 0x91, 0x49, 0x4e, 0x68, 0x5b, 0x81, 0x83, 0x88, 0xff, 0x0a, 0xc1, 0xaf,
	0x3f, 0x46, 0x96, 0x50, 0xde, 0x1f, 0xed, 0x4b, 0xd8, 0xdf, 0x89, 0x59, 0x03, 0xc2, 0x47, 0x5c,
	0x6f, 0xb6, 0x58, 0x3c, 0xd9, 0x21, 0xfc, 0x5b, 0x8a, 0xa7, 0x1c, 0x37, 0xfb, 0x2b, 0xc5, 0x45,
	0xe5, 0x3c, 0x18, 0xbe, 0x40, 0x47, 0xea, 0x6f, 0x01, 0x87, 0x0d, 0x0f, 0x2f, 0x2e, 0xd2, 0x38,
	0xb8, 0xbf, 0xfd, 0xc5, 0x21, 0xcd, 0x50, 0xf5, 0x67, 0xbb, 0xa7, 0x93, 0x54, 0x5d, 0x78, 0xf6,
	0x1e, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xeb, 0x95, 0x61, 0x9b, 0x02, 0x00, 0x00,
}
