// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/web/v1/web.proto

package v1 // import "github.com/census-instrumentation/opencensus-proto/gen-go/web/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Type of span. Can be used to specify additional relationships between
// spans in addition to a parent/child relationship.
type Interaction_Span_SpanKind int32

const (
	// Unspecified.
	Interaction_Span_SPAN_KIND_UNSPECIFIED Interaction_Span_SpanKind = 0
	// Indicates that the span covers server-side handling of an RPC or other
	// remote network request.
	Interaction_Span_SERVER Interaction_Span_SpanKind = 1
	// Indicates that the span covers the client-side wrapper around an RPC or
	// other remote request.
	// These will be joined with browser performance data.
	Interaction_Span_CLIENT Interaction_Span_SpanKind = 2
)

var Interaction_Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "SERVER",
	2: "CLIENT",
}
var Interaction_Span_SpanKind_value = map[string]int32{
	"SPAN_KIND_UNSPECIFIED": 0,
	"SERVER":                1,
	"CLIENT":                2,
}

func (x Interaction_Span_SpanKind) String() string {
	return proto.EnumName(Interaction_Span_SpanKind_name, int32(x))
}
func (Interaction_Span_SpanKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 0}
}

// Indicates whether the message was sent or received.
type Interaction_Span_MessageEvent_Type int32

const (
	// Unknown event type.
	Interaction_Span_MessageEvent_TYPE_UNSPECIFIED Interaction_Span_MessageEvent_Type = 0
	// Indicates a sent message.
	Interaction_Span_MessageEvent_SENT Interaction_Span_MessageEvent_Type = 1
	// Indicates a received message.
	Interaction_Span_MessageEvent_RECEIVED Interaction_Span_MessageEvent_Type = 2
)

var Interaction_Span_MessageEvent_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "SENT",
	2: "RECEIVED",
}
var Interaction_Span_MessageEvent_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"SENT":             1,
	"RECEIVED":         2,
}

func (x Interaction_Span_MessageEvent_Type) String() string {
	return proto.EnumName(Interaction_Span_MessageEvent_Type_name, int32(x))
}
func (Interaction_Span_MessageEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 2, 0}
}

// The relationship of the current span relative to the linked span:
// child, parent, or unspecified.
type Interaction_Span_Link_Type int32

const (
	// The relationship of the two spans is unknown, or known but other
	// than parent-child.
	Interaction_Span_Link_UNSPECIFIED Interaction_Span_Link_Type = 0
	// The linked span is a child of the current span.
	Interaction_Span_Link_CHILD_LINKED_SPAN Interaction_Span_Link_Type = 1
	// The linked span is a parent of the current span.
	Interaction_Span_Link_PARENT_LINKED_SPAN Interaction_Span_Link_Type = 2
)

var Interaction_Span_Link_Type_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CHILD_LINKED_SPAN",
	2: "PARENT_LINKED_SPAN",
}
var Interaction_Span_Link_Type_value = map[string]int32{
	"UNSPECIFIED":        0,
	"CHILD_LINKED_SPAN":  1,
	"PARENT_LINKED_SPAN": 2,
}

func (x Interaction_Span_Link_Type) String() string {
	return proto.EnumName(Interaction_Span_Link_Type_name, int32(x))
}
func (Interaction_Span_Link_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 3, 0}
}

// A measurable user interaction within a web browser client. This could be an
// initial page load, a route transition within a single page application, or an
// on-page user interaction such as clicking a button. This proto contains all
// the information needed for the web interaction interceptor to generate spans
// and metrics related to the interaction.
type Interaction struct {
	// The trace ID for the user interaction. All spans within an interaction are
	// part of the same trace. The ID is a 16-byte array encoded in hexadecimal.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// The time origin of the performance clock in the browser session that
	// collected this interaction, measured as milliseconds since the epoch.
	// See https://www.w3.org/TR/hr-time/
	TimeOrigin float64 `protobuf:"fixed64,2,opt,name=time_origin,json=timeOrigin,proto3" json:"time_origin,omitempty"`
	// The time in milliseconds since the epoch that the frontend web server
	// received the request to render the initial template for the web UI. This
	// time is measured by the server's clock and is used to adjust for clock skew
	// between the client and server. This should be sent from the web server to
	// client as a value in a <script> tag in the rendered HTML. A value of 0
	// indicates that it is missing.
	ServerRequestStart float64 `protobuf:"fixed64,3,opt,name=server_request_start,json=serverRequestStart,proto3" json:"server_request_start,omitempty"`
	// The time in milliseconds since the epoch that the frontend web server
	// started sending the response to render the web UI template. This is
	// measured by the server clock and is used to adjust for clock skew between
	// client and server. This should also be sent from server to client via the
	// rendered HTML, and a value of 0 indicates that it is missing.
	ServerResponseStart float64 `protobuf:"fixed64,4,opt,name=server_response_start,json=serverResponseStart,proto3" json:"server_response_start,omitempty"`
	// Web performance entries associated with the interaction.
	PerformanceEntries []*Interaction_PerformanceEntry `protobuf:"bytes,5,rep,name=performance_entries,json=performanceEntries,proto3" json:"performance_entries,omitempty"`
	Spans              []*Interaction_Span             `protobuf:"bytes,6,rep,name=spans,proto3" json:"spans,omitempty"`
	// OpenCensus web library info.
	LibraryInfo *Interaction_LibraryInfo `protobuf:"bytes,7,opt,name=library_info,json=libraryInfo,proto3" json:"library_info,omitempty"`
	// Service description for the web UI.
	ServiceInfo *Interaction_ServiceInfo `protobuf:"bytes,8,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	// Attributes associated with web client that generated the interaction. This
	// could be related to the end user (e.g. user ID, session ID) or could be
	// related to the web UI service (e.g. serving region, environment type).
	// This plays a similar role to the Node `attributes` field.
	// See
	// https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/common/v1/common.proto
	ClientAttributes     map[string]string `protobuf:"bytes,9,rep,name=client_attributes,json=clientAttributes,proto3" json:"client_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Interaction) Reset()         { *m = Interaction{} }
func (m *Interaction) String() string { return proto.CompactTextString(m) }
func (*Interaction) ProtoMessage()    {}
func (*Interaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0}
}
func (m *Interaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction.Unmarshal(m, b)
}
func (m *Interaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction.Marshal(b, m, deterministic)
}
func (dst *Interaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction.Merge(dst, src)
}
func (m *Interaction) XXX_Size() int {
	return xxx_messageInfo_Interaction.Size(m)
}
func (m *Interaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction proto.InternalMessageInfo

func (m *Interaction) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Interaction) GetTimeOrigin() float64 {
	if m != nil {
		return m.TimeOrigin
	}
	return 0
}

func (m *Interaction) GetServerRequestStart() float64 {
	if m != nil {
		return m.ServerRequestStart
	}
	return 0
}

func (m *Interaction) GetServerResponseStart() float64 {
	if m != nil {
		return m.ServerResponseStart
	}
	return 0
}

func (m *Interaction) GetPerformanceEntries() []*Interaction_PerformanceEntry {
	if m != nil {
		return m.PerformanceEntries
	}
	return nil
}

func (m *Interaction) GetSpans() []*Interaction_Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *Interaction) GetLibraryInfo() *Interaction_LibraryInfo {
	if m != nil {
		return m.LibraryInfo
	}
	return nil
}

func (m *Interaction) GetServiceInfo() *Interaction_ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *Interaction) GetClientAttributes() map[string]string {
	if m != nil {
		return m.ClientAttributes
	}
	return nil
}

// Performance data from `performance.getEntries()` retrieved after this
// interaction ended. All timings are in milleconds since the browser
// navigation start. Values may be zero if the browser security policy
// does not permit reading the field, e.g. if the resource requested is
// from another domain and no matching Timing-Allow-Origin header is sent.
// See detailed specs at:
// https://www.w3.org/TR/performance-timeline-2/
// https://www.w3.org/TR/resource-timing-2/
// https://www.w3.org/TR/navigation-timing-2/
// https://www.w3.org/TR/server-timing/
//
// Sending the raw performance entries allows the JavaScript client code
// o be smaller. The OpenCensus agent web interceptor can use these entries to
// generate detailed spans.
type Interaction_PerformanceEntry struct {
	// Type of performnce entry e.g. "navigation" or "resource".
	EntryType string `protobuf:"bytes,1,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	// The first timestamp of the entry, e.g. for a resource timing, the time
	// right before the browser starts the fetch.
	StartTime float64 `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The duration of the performance entry in milliseconds.
	Duration float64 `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	// URL of the retrieved resource or page.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// The type of navigation for a navigation entry.
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// The type of resource that initiated the performance event.
	InitiatorType string `protobuf:"bytes,6,opt,name=initiator_type,json=initiatorType,proto3" json:"initiator_type,omitempty"`
	// If the document has an active service worker registration, this is
	// time right before the browser ran the worker or fired the `fetch` event.
	WorkerStart float64 `protobuf:"fixed64,7,opt,name=worker_start,json=workerStart,proto3" json:"worker_start,omitempty"`
	// If there are HTTP redirects when navigating and if all are from the same
	// origin, this is the start time of the fetch that initiated the redirect.
	RedirectStart float64 `protobuf:"fixed64,8,opt,name=redirect_start,json=redirectStart,proto3" json:"redirect_start,omitempty"`
	// Number of redirects since the last non-redirect navigation.
	RedirectCount int32 `protobuf:"varint,9,opt,name=redirect_count,json=redirectCount,proto3" json:"redirect_count,omitempty"`
	// The time right after receiving the last byte of the last redirect.
	RedirectEnd float64 `protobuf:"fixed64,10,opt,name=redirect_end,json=redirectEnd,proto3" json:"redirect_end,omitempty"`
	// Time right before the browser checks caches for a resource.
	FetchStart float64 `protobuf:"fixed64,11,opt,name=fetch_start,json=fetchStart,proto3" json:"fetch_start,omitempty"`
	// Time right before the browser starts the domain name lookup.
	DomainLookupStart float64 `protobuf:"fixed64,12,opt,name=domain_lookup_start,json=domainLookupStart,proto3" json:"domain_lookup_start,omitempty"`
	// Time right after the browser finishes the domain name lookup.
	DomainLookupEnd float64 `protobuf:"fixed64,13,opt,name=domain_lookup_end,json=domainLookupEnd,proto3" json:"domain_lookup_end,omitempty"`
	// Time right before the browser starts establishing the server connection.
	// If a persistent connection is used or the resource is retrieved from
	// cache, this will match domain_lookup_end.
	ConnectStart float64 `protobuf:"fixed64,14,opt,name=connect_start,json=connectStart,proto3" json:"connect_start,omitempty"`
	// Time right before the browser starts the handshake to secure the
	// connection, or zero if a secure connection is not used.
	SecureConnectionStart float64 `protobuf:"fixed64,15,opt,name=secure_connection_start,json=secureConnectionStart,proto3" json:"secure_connection_start,omitempty"`
	// Time right after the browser finishes establishing the connection.
	// If a persistent connection is used or the resource is retrieved from
	// cache, this will match domain_lookup_end.
	ConnectEnd float64 `protobuf:"fixed64,16,opt,name=connect_end,json=connectEnd,proto3" json:"connect_end,omitempty"`
	// Network protocol used to fetch the resource by ALPN Protocol ID.
	NextHopProtocol string `protobuf:"bytes,17,opt,name=next_hop_protocol,json=nextHopProtocol,proto3" json:"next_hop_protocol,omitempty"`
	// Time right before the browser starts requesting the resource.
	RequestStart float64 `protobuf:"fixed64,18,opt,name=request_start,json=requestStart,proto3" json:"request_start,omitempty"`
	// Time right after the browser receives the first byte of the response.
	ResponseStart float64 `protobuf:"fixed64,19,opt,name=response_start,json=responseStart,proto3" json:"response_start,omitempty"`
	// Time right after the browser receives the last byte of the response.
	ResponseEnd float64 `protobuf:"fixed64,20,opt,name=response_end,json=responseEnd,proto3" json:"response_end,omitempty"`
	// Number of bytes received from a HTTP fetch from both headers and payload.
	TransferSize int64 `protobuf:"varint,21,opt,name=transfer_size,json=transferSize,proto3" json:"transfer_size,omitempty"`
	// Compressed size of the payload body in bytes.
	EncodedBodySize int64 `protobuf:"varint,22,opt,name=encoded_body_size,json=encodedBodySize,proto3" json:"encoded_body_size,omitempty"`
	// Uncompressed size of the payload body in bytes.
	DecodedBodySize int64 `protobuf:"varint,23,opt,name=decoded_body_size,json=decodedBodySize,proto3" json:"decoded_body_size,omitempty"`
	// Server timings associated with the performance entry.
	ServerTiming []*Interaction_PerformanceEntry_PerformanceServerTiming `protobuf:"bytes,24,rep,name=server_timing,json=serverTiming,proto3" json:"server_timing,omitempty"`
	// Time right before browser starts the unload event of previous document.
	// If previous document was from different origin, this is zero.
	UnloadEventStart float64 `protobuf:"fixed64,25,opt,name=unload_event_start,json=unloadEventStart,proto3" json:"unload_event_start,omitempty"`
	// Time right after browser finishes the unload event of previous document.
	// If previous document was from different origin, this is zero.
	UnloadEventEnd float64 `protobuf:"fixed64,26,opt,name=unload_event_end,json=unloadEventEnd,proto3" json:"unload_event_end,omitempty"`
	// Time right before the browser sets document readiness to "interactive".
	DomInteractive float64 `protobuf:"fixed64,27,opt,name=dom_interactive,json=domInteractive,proto3" json:"dom_interactive,omitempty"`
	// Time right before the browser fires DOMContentLoaded event.
	DomContentLoadedEventStart float64 `protobuf:"fixed64,28,opt,name=dom_content_loaded_event_start,json=domContentLoadedEventStart,proto3" json:"dom_content_loaded_event_start,omitempty"`
	// Time right after the DOMContentLoaded event completes.
	DomContentLoadedEventEnd float64 `protobuf:"fixed64,29,opt,name=dom_content_loaded_event_end,json=domContentLoadedEventEnd,proto3" json:"dom_content_loaded_event_end,omitempty"`
	// Time right before the browser sets document readiness to "complete".
	DomComplete float64 `protobuf:"fixed64,30,opt,name=dom_complete,json=domComplete,proto3" json:"dom_complete,omitempty"`
	// Time right before the load event of the current document is fired.
	LoadEventEnd float64 `protobuf:"fixed64,31,opt,name=load_event_end,json=loadEventEnd,proto3" json:"load_event_end,omitempty"`
	// Time when the load event of the current document is completed.
	LoadEventStart float64 `protobuf:"fixed64,32,opt,name=load_event_start,json=loadEventStart,proto3" json:"load_event_start,omitempty"`
	// Deprecated in Navigation Timing Level 2 Spec.
	// Time when the browser sets document readiness to "loading".
	// Due to browser differences this should not be used in meaningful metrics.
	DomLoading           float64  `protobuf:"fixed64,33,opt,name=dom_loading,json=domLoading,proto3" json:"dom_loading,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interaction_PerformanceEntry) Reset()         { *m = Interaction_PerformanceEntry{} }
func (m *Interaction_PerformanceEntry) String() string { return proto.CompactTextString(m) }
func (*Interaction_PerformanceEntry) ProtoMessage()    {}
func (*Interaction_PerformanceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 0}
}
func (m *Interaction_PerformanceEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_PerformanceEntry.Unmarshal(m, b)
}
func (m *Interaction_PerformanceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_PerformanceEntry.Marshal(b, m, deterministic)
}
func (dst *Interaction_PerformanceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_PerformanceEntry.Merge(dst, src)
}
func (m *Interaction_PerformanceEntry) XXX_Size() int {
	return xxx_messageInfo_Interaction_PerformanceEntry.Size(m)
}
func (m *Interaction_PerformanceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_PerformanceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_PerformanceEntry proto.InternalMessageInfo

func (m *Interaction_PerformanceEntry) GetEntryType() string {
	if m != nil {
		return m.EntryType
	}
	return ""
}

func (m *Interaction_PerformanceEntry) GetStartTime() float64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interaction_PerformanceEntry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Interaction_PerformanceEntry) GetInitiatorType() string {
	if m != nil {
		return m.InitiatorType
	}
	return ""
}

func (m *Interaction_PerformanceEntry) GetWorkerStart() float64 {
	if m != nil {
		return m.WorkerStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetRedirectStart() float64 {
	if m != nil {
		return m.RedirectStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetRedirectCount() int32 {
	if m != nil {
		return m.RedirectCount
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetRedirectEnd() float64 {
	if m != nil {
		return m.RedirectEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetFetchStart() float64 {
	if m != nil {
		return m.FetchStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomainLookupStart() float64 {
	if m != nil {
		return m.DomainLookupStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomainLookupEnd() float64 {
	if m != nil {
		return m.DomainLookupEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetConnectStart() float64 {
	if m != nil {
		return m.ConnectStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetSecureConnectionStart() float64 {
	if m != nil {
		return m.SecureConnectionStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetConnectEnd() float64 {
	if m != nil {
		return m.ConnectEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetNextHopProtocol() string {
	if m != nil {
		return m.NextHopProtocol
	}
	return ""
}

func (m *Interaction_PerformanceEntry) GetRequestStart() float64 {
	if m != nil {
		return m.RequestStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetResponseStart() float64 {
	if m != nil {
		return m.ResponseStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetResponseEnd() float64 {
	if m != nil {
		return m.ResponseEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetTransferSize() int64 {
	if m != nil {
		return m.TransferSize
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetEncodedBodySize() int64 {
	if m != nil {
		return m.EncodedBodySize
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDecodedBodySize() int64 {
	if m != nil {
		return m.DecodedBodySize
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetServerTiming() []*Interaction_PerformanceEntry_PerformanceServerTiming {
	if m != nil {
		return m.ServerTiming
	}
	return nil
}

func (m *Interaction_PerformanceEntry) GetUnloadEventStart() float64 {
	if m != nil {
		return m.UnloadEventStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetUnloadEventEnd() float64 {
	if m != nil {
		return m.UnloadEventEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomInteractive() float64 {
	if m != nil {
		return m.DomInteractive
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomContentLoadedEventStart() float64 {
	if m != nil {
		return m.DomContentLoadedEventStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomContentLoadedEventEnd() float64 {
	if m != nil {
		return m.DomContentLoadedEventEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomComplete() float64 {
	if m != nil {
		return m.DomComplete
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetLoadEventEnd() float64 {
	if m != nil {
		return m.LoadEventEnd
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetLoadEventStart() float64 {
	if m != nil {
		return m.LoadEventStart
	}
	return 0
}

func (m *Interaction_PerformanceEntry) GetDomLoading() float64 {
	if m != nil {
		return m.DomLoading
	}
	return 0
}

// Timing entries sent by the server via the Server-Timing header.
// See https://www.w3.org/TR/server-timing/
type Interaction_PerformanceEntry_PerformanceServerTiming struct {
	// Metric name sent by the server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Metric description sent by the server.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Metric value sent by the server.
	Duration             *wrappers.DoubleValue `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Interaction_PerformanceEntry_PerformanceServerTiming) Reset() {
	*m = Interaction_PerformanceEntry_PerformanceServerTiming{}
}
func (m *Interaction_PerformanceEntry_PerformanceServerTiming) String() string {
	return proto.CompactTextString(m)
}
func (*Interaction_PerformanceEntry_PerformanceServerTiming) ProtoMessage() {}
func (*Interaction_PerformanceEntry_PerformanceServerTiming) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 0, 0}
}
func (m *Interaction_PerformanceEntry_PerformanceServerTiming) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming.Unmarshal(m, b)
}
func (m *Interaction_PerformanceEntry_PerformanceServerTiming) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming.Marshal(b, m, deterministic)
}
func (dst *Interaction_PerformanceEntry_PerformanceServerTiming) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming.Merge(dst, src)
}
func (m *Interaction_PerformanceEntry_PerformanceServerTiming) XXX_Size() int {
	return xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming.Size(m)
}
func (m *Interaction_PerformanceEntry_PerformanceServerTiming) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_PerformanceEntry_PerformanceServerTiming proto.InternalMessageInfo

func (m *Interaction_PerformanceEntry_PerformanceServerTiming) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interaction_PerformanceEntry_PerformanceServerTiming) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Interaction_PerformanceEntry_PerformanceServerTiming) GetDuration() *wrappers.DoubleValue {
	if m != nil {
		return m.Duration
	}
	return nil
}

// A Span is similar to main OpenCensus Span, but is designed to be easier
// for browser JavaScript to write via HTTP-JSON that will be converted to
// the proto via jsonpb. All spans for an interaction are assumed to have the
// same trace ID, specified above (otherwise send two interactions with
// links).
// See
// https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace.proto
type Interaction_Span struct {
	// A unique identifier for a span within the interaction. It is 8-bytes
	// encoded as a hexadecimal string.
	SpanId string `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Information about request position in multiple distributed tracing
	// graphs. See https://github.com/w3c/distributed-tracing for details.
	Tracestate map[string]string `protobuf:"bytes,2,rep,name=tracestate,proto3" json:"tracestate,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The `span_id` of this span's parent span. If this is a root span, then
	// this field must be empty. It is 8-bytes encoded as a hexadecimal string.
	ParentSpanId string `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// A description of the span's operation.
	Name string                    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind Interaction_Span_SpanKind `protobuf:"varint,5,opt,name=kind,proto3,enum=opencensus.proto.web.v1.Interaction_Span_SpanKind" json:"kind,omitempty"`
	// Span start time as measured by browser performance clock (the result of
	// calling `performance.now()`). This is the number of milliseconds since
	// the browser clock timeOrigin (the start of the navigation).
	// If this value is missing for an HTTP network call span, it can be
	// inferred from the web performance entry for that network call.
	Start *wrappers.DoubleValue `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	// Span end time in browser performance clock milliseconds.
	// If this value is missing for an HTTP network call span, it can be
	// inferred from the web performance entry for that network call.
	End *wrappers.DoubleValue `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	// Attributes associated with the span. Defining this as a Struct makes it
	// easier for the JavaScript client to send attributes as normal JSON
	// values. JSON booleans, strings and numbers will be converted to the
	// trace.v1.Span.AttributeValue string_value, bool_value or double_value
	// fields respectively. To specify an int value in JSON use e.g.
	// {intValue:"2"} as the attribute value.
	Attributes *_struct.Struct `protobuf:"bytes,8,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Unparse JavaScript stack trace associated with this span. This will be
	// the value of `Error.stack`.
	StackTrace string `protobuf:"bytes,9,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// Time stamped text annotations for events associated with the span.
	Annotations []*Interaction_Span_Annotation `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty"`
	// Message events associated with the span
	MessageEvents []*Interaction_Span_MessageEvent `protobuf:"bytes,11,rep,name=message_events,json=messageEvents,proto3" json:"message_events,omitempty"`
	Links         []*Interaction_Span_Link         `protobuf:"bytes,12,rep,name=links,proto3" json:"links,omitempty"`
	Status        *Interaction_Span_Status         `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	// A highly recommended but not required flag that identifies when a trace
	// crosses a process boundary. True when the parent_span belongs to the
	// same process as the current span.
	// This will typically be defaulted to true by the web interceptor.
	SameProcessAsParentSpan *wrappers.BoolValue `protobuf:"bytes,14,opt,name=same_process_as_parent_span,json=sameProcessAsParentSpan,proto3" json:"same_process_as_parent_span,omitempty"`
	// An optional number of child spans that were generated while this span
	// was active. If set, allows an implementation to detect missing child
	// spans. This will typically be computed automatically by the interceptor.
	ChildSpanCount       *wrappers.UInt32Value `protobuf:"bytes,15,opt,name=child_span_count,json=childSpanCount,proto3" json:"child_span_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Interaction_Span) Reset()         { *m = Interaction_Span{} }
func (m *Interaction_Span) String() string { return proto.CompactTextString(m) }
func (*Interaction_Span) ProtoMessage()    {}
func (*Interaction_Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1}
}
func (m *Interaction_Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_Span.Unmarshal(m, b)
}
func (m *Interaction_Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_Span.Marshal(b, m, deterministic)
}
func (dst *Interaction_Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_Span.Merge(dst, src)
}
func (m *Interaction_Span) XXX_Size() int {
	return xxx_messageInfo_Interaction_Span.Size(m)
}
func (m *Interaction_Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_Span proto.InternalMessageInfo

func (m *Interaction_Span) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *Interaction_Span) GetTracestate() map[string]string {
	if m != nil {
		return m.Tracestate
	}
	return nil
}

func (m *Interaction_Span) GetParentSpanId() string {
	if m != nil {
		return m.ParentSpanId
	}
	return ""
}

func (m *Interaction_Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interaction_Span) GetKind() Interaction_Span_SpanKind {
	if m != nil {
		return m.Kind
	}
	return Interaction_Span_SPAN_KIND_UNSPECIFIED
}

func (m *Interaction_Span) GetStart() *wrappers.DoubleValue {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Interaction_Span) GetEnd() *wrappers.DoubleValue {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Interaction_Span) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Interaction_Span) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *Interaction_Span) GetAnnotations() []*Interaction_Span_Annotation {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Interaction_Span) GetMessageEvents() []*Interaction_Span_MessageEvent {
	if m != nil {
		return m.MessageEvents
	}
	return nil
}

func (m *Interaction_Span) GetLinks() []*Interaction_Span_Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Interaction_Span) GetStatus() *Interaction_Span_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Interaction_Span) GetSameProcessAsParentSpan() *wrappers.BoolValue {
	if m != nil {
		return m.SameProcessAsParentSpan
	}
	return nil
}

func (m *Interaction_Span) GetChildSpanCount() *wrappers.UInt32Value {
	if m != nil {
		return m.ChildSpanCount
	}
	return nil
}

// A time stamped text annotation with a set of attributes.
type Interaction_Span_Annotation struct {
	// Time the event occurred in performance clock milliseconds.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// Attributes for the event.
	Attributes           *_struct.Struct `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Interaction_Span_Annotation) Reset()         { *m = Interaction_Span_Annotation{} }
func (m *Interaction_Span_Annotation) String() string { return proto.CompactTextString(m) }
func (*Interaction_Span_Annotation) ProtoMessage()    {}
func (*Interaction_Span_Annotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 1}
}
func (m *Interaction_Span_Annotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_Span_Annotation.Unmarshal(m, b)
}
func (m *Interaction_Span_Annotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_Span_Annotation.Marshal(b, m, deterministic)
}
func (dst *Interaction_Span_Annotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_Span_Annotation.Merge(dst, src)
}
func (m *Interaction_Span_Annotation) XXX_Size() int {
	return xxx_messageInfo_Interaction_Span_Annotation.Size(m)
}
func (m *Interaction_Span_Annotation) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_Span_Annotation.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_Span_Annotation proto.InternalMessageInfo

func (m *Interaction_Span_Annotation) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Interaction_Span_Annotation) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// An event describing a message sent/received between Spans.
type Interaction_Span_MessageEvent struct {
	// Time the message was sent/received in performance clock milliseconds.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// MessageEvent type. Indicates whether the message was sent or received.
	Type Interaction_Span_MessageEvent_Type `protobuf:"varint,2,opt,name=type,proto3,enum=opencensus.proto.web.v1.Interaction_Span_MessageEvent_Type" json:"type,omitempty"`
	// An identifier for the MessageEvent's message that can be used to match
	// SENT and RECEIVED MessageEvents. For example, this field could
	// represent a sequence ID for a streaming RPC. It is recommended to be
	// unique within a Span.
	Id uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// The number of uncompressed bytes sent or received.
	UncompressedSize uint64 `protobuf:"varint,4,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	// The number of compressed bytes sent or received. If zero, assumed to
	// be the same size as uncompressed.
	CompressedSize       uint64   `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interaction_Span_MessageEvent) Reset()         { *m = Interaction_Span_MessageEvent{} }
func (m *Interaction_Span_MessageEvent) String() string { return proto.CompactTextString(m) }
func (*Interaction_Span_MessageEvent) ProtoMessage()    {}
func (*Interaction_Span_MessageEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 2}
}
func (m *Interaction_Span_MessageEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_Span_MessageEvent.Unmarshal(m, b)
}
func (m *Interaction_Span_MessageEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_Span_MessageEvent.Marshal(b, m, deterministic)
}
func (dst *Interaction_Span_MessageEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_Span_MessageEvent.Merge(dst, src)
}
func (m *Interaction_Span_MessageEvent) XXX_Size() int {
	return xxx_messageInfo_Interaction_Span_MessageEvent.Size(m)
}
func (m *Interaction_Span_MessageEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_Span_MessageEvent.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_Span_MessageEvent proto.InternalMessageInfo

func (m *Interaction_Span_MessageEvent) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Interaction_Span_MessageEvent) GetType() Interaction_Span_MessageEvent_Type {
	if m != nil {
		return m.Type
	}
	return Interaction_Span_MessageEvent_TYPE_UNSPECIFIED
}

func (m *Interaction_Span_MessageEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Interaction_Span_MessageEvent) GetUncompressedSize() uint64 {
	if m != nil {
		return m.UncompressedSize
	}
	return 0
}

func (m *Interaction_Span_MessageEvent) GetCompressedSize() uint64 {
	if m != nil {
		return m.CompressedSize
	}
	return 0
}

// A pointer from the current span to another span in the same trace or in a
// different trace. For example, this can be used in batching operations,
// where a single batch handler processes multiple requests from different
// traces or when the handler receives a request from a different project.
type Interaction_Span_Link struct {
	// Unique identifier for linked trace. It is a 16-byte hex-encoded string.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Unique identifier for span within linked trace. It is a 16-byte
	// hex-encoded string.
	SpanId string                     `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Type   Interaction_Span_Link_Type `protobuf:"varint,3,opt,name=type,proto3,enum=opencensus.proto.web.v1.Interaction_Span_Link_Type" json:"type,omitempty"`
	// Attributes about the trace link.
	Attributes           *_struct.Struct `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Interaction_Span_Link) Reset()         { *m = Interaction_Span_Link{} }
func (m *Interaction_Span_Link) String() string { return proto.CompactTextString(m) }
func (*Interaction_Span_Link) ProtoMessage()    {}
func (*Interaction_Span_Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 3}
}
func (m *Interaction_Span_Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_Span_Link.Unmarshal(m, b)
}
func (m *Interaction_Span_Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_Span_Link.Marshal(b, m, deterministic)
}
func (dst *Interaction_Span_Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_Span_Link.Merge(dst, src)
}
func (m *Interaction_Span_Link) XXX_Size() int {
	return xxx_messageInfo_Interaction_Span_Link.Size(m)
}
func (m *Interaction_Span_Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_Span_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_Span_Link proto.InternalMessageInfo

func (m *Interaction_Span_Link) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Interaction_Span_Link) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *Interaction_Span_Link) GetType() Interaction_Span_Link_Type {
	if m != nil {
		return m.Type
	}
	return Interaction_Span_Link_UNSPECIFIED
}

func (m *Interaction_Span_Link) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// The `Status` type defines a logical error model that is suitable for
// different programming environments, including REST APIs and RPC APIs.
// This proto's fields are a subset of those of
// [google.rpc.Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto),
// which is used by [gRPC](https://github.com/grpc).
type Interaction_Span_Status struct {
	// The HTTP status code associated with the span.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing error message, which should be in English.
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interaction_Span_Status) Reset()         { *m = Interaction_Span_Status{} }
func (m *Interaction_Span_Status) String() string { return proto.CompactTextString(m) }
func (*Interaction_Span_Status) ProtoMessage()    {}
func (*Interaction_Span_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 1, 4}
}
func (m *Interaction_Span_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_Span_Status.Unmarshal(m, b)
}
func (m *Interaction_Span_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_Span_Status.Marshal(b, m, deterministic)
}
func (dst *Interaction_Span_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_Span_Status.Merge(dst, src)
}
func (m *Interaction_Span_Status) XXX_Size() int {
	return xxx_messageInfo_Interaction_Span_Status.Size(m)
}
func (m *Interaction_Span_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_Span_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_Span_Status proto.InternalMessageInfo

func (m *Interaction_Span_Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Interaction_Span_Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Information about the OpenCensus web library that measured the interaction.
// This is a simplified version of the LibraryInfo message used to write
// server side Spans. There is no `Language` field currently as we assume the
// language writing web interaction data is browser JavaScript. See
// https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/common/v1/common.proto
type Interaction_LibraryInfo struct {
	// The version of the OpenCensus web client library.
	LibraryVersion string `protobuf:"bytes,2,opt,name=library_version,json=libraryVersion,proto3" json:"library_version,omitempty"`
	// The version of the OpenCensus web Agent exporter library. If omitted,
	// this is assumed to be the same as `library_version`.
	ExporterVersion      string   `protobuf:"bytes,3,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interaction_LibraryInfo) Reset()         { *m = Interaction_LibraryInfo{} }
func (m *Interaction_LibraryInfo) String() string { return proto.CompactTextString(m) }
func (*Interaction_LibraryInfo) ProtoMessage()    {}
func (*Interaction_LibraryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 2}
}
func (m *Interaction_LibraryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_LibraryInfo.Unmarshal(m, b)
}
func (m *Interaction_LibraryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_LibraryInfo.Marshal(b, m, deterministic)
}
func (dst *Interaction_LibraryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_LibraryInfo.Merge(dst, src)
}
func (m *Interaction_LibraryInfo) XXX_Size() int {
	return xxx_messageInfo_Interaction_LibraryInfo.Size(m)
}
func (m *Interaction_LibraryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_LibraryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_LibraryInfo proto.InternalMessageInfo

func (m *Interaction_LibraryInfo) GetLibraryVersion() string {
	if m != nil {
		return m.LibraryVersion
	}
	return ""
}

func (m *Interaction_LibraryInfo) GetExporterVersion() string {
	if m != nil {
		return m.ExporterVersion
	}
	return ""
}

// Service description for the web UI that generated the interaction.
type Interaction_ServiceInfo struct {
	// Name of the service.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interaction_ServiceInfo) Reset()         { *m = Interaction_ServiceInfo{} }
func (m *Interaction_ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*Interaction_ServiceInfo) ProtoMessage()    {}
func (*Interaction_ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_3382f66f17363007, []int{0, 3}
}
func (m *Interaction_ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interaction_ServiceInfo.Unmarshal(m, b)
}
func (m *Interaction_ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interaction_ServiceInfo.Marshal(b, m, deterministic)
}
func (dst *Interaction_ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interaction_ServiceInfo.Merge(dst, src)
}
func (m *Interaction_ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_Interaction_ServiceInfo.Size(m)
}
func (m *Interaction_ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Interaction_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Interaction_ServiceInfo proto.InternalMessageInfo

func (m *Interaction_ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Interaction)(nil), "opencensus.proto.web.v1.Interaction")
	proto.RegisterMapType((map[string]string)(nil), "opencensus.proto.web.v1.Interaction.ClientAttributesEntry")
	proto.RegisterType((*Interaction_PerformanceEntry)(nil), "opencensus.proto.web.v1.Interaction.PerformanceEntry")
	proto.RegisterType((*Interaction_PerformanceEntry_PerformanceServerTiming)(nil), "opencensus.proto.web.v1.Interaction.PerformanceEntry.PerformanceServerTiming")
	proto.RegisterType((*Interaction_Span)(nil), "opencensus.proto.web.v1.Interaction.Span")
	proto.RegisterMapType((map[string]string)(nil), "opencensus.proto.web.v1.Interaction.Span.TracestateEntry")
	proto.RegisterType((*Interaction_Span_Annotation)(nil), "opencensus.proto.web.v1.Interaction.Span.Annotation")
	proto.RegisterType((*Interaction_Span_MessageEvent)(nil), "opencensus.proto.web.v1.Interaction.Span.MessageEvent")
	proto.RegisterType((*Interaction_Span_Link)(nil), "opencensus.proto.web.v1.Interaction.Span.Link")
	proto.RegisterType((*Interaction_Span_Status)(nil), "opencensus.proto.web.v1.Interaction.Span.Status")
	proto.RegisterType((*Interaction_LibraryInfo)(nil), "opencensus.proto.web.v1.Interaction.LibraryInfo")
	proto.RegisterType((*Interaction_ServiceInfo)(nil), "opencensus.proto.web.v1.Interaction.ServiceInfo")
	proto.RegisterEnum("opencensus.proto.web.v1.Interaction_Span_SpanKind", Interaction_Span_SpanKind_name, Interaction_Span_SpanKind_value)
	proto.RegisterEnum("opencensus.proto.web.v1.Interaction_Span_MessageEvent_Type", Interaction_Span_MessageEvent_Type_name, Interaction_Span_MessageEvent_Type_value)
	proto.RegisterEnum("opencensus.proto.web.v1.Interaction_Span_Link_Type", Interaction_Span_Link_Type_name, Interaction_Span_Link_Type_value)
}

func init() {
	proto.RegisterFile("github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/web/v1/web.proto", fileDescriptor_web_3382f66f17363007)
}

var fileDescriptor_web_3382f66f17363007 = []byte{
	// 1687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x5f, 0x73, 0x1b, 0xb7,
	0x11, 0x2f, 0x29, 0x52, 0x7f, 0xf6, 0x28, 0x92, 0x82, 0xad, 0xe8, 0x7c, 0x71, 0x6c, 0xda, 0x6d,
	0x26, 0x4a, 0xda, 0x50, 0x09, 0x9d, 0xba, 0x69, 0x3a, 0x69, 0x2b, 0x51, 0x74, 0xcd, 0xb1, 0xa2,
	0x70, 0x8e, 0x8a, 0x1a, 0x77, 0xa6, 0x73, 0x73, 0xbc, 0x83, 0x68, 0x8c, 0x48, 0xe0, 0x0a, 0x80,
	0x72, 0x94, 0x67, 0xbf, 0xf4, 0xa9, 0x9f, 0xac, 0x9f, 0xa8, 0x2f, 0x1d, 0x2c, 0x40, 0xf2, 0x48,
	0x4b, 0x19, 0xda, 0x2f, 0xf6, 0xe1, 0xb7, 0xbf, 0x5d, 0x2c, 0x76, 0x17, 0x8b, 0xa5, 0xe0, 0xc7,
	0x21, 0xd3, 0xaf, 0x26, 0x83, 0x66, 0x22, 0xc6, 0x07, 0x09, 0xe5, 0x6a, 0xa2, 0x3e, 0x67, 0x5c,
	0x69, 0x39, 0x19, 0x53, 0xae, 0x63, 0xcd, 0x04, 0x3f, 0x10, 0x19, 0xe5, 0x4e, 0x94, 0x49, 0xa1,
	0xc5, 0x81, 0x92, 0x49, 0x0e, 0x3c, 0xb0, 0xe0, 0x6b, 0x3a, 0x38, 0xb8, 0xfa, 0xd2, 0xfc, 0xd7,
	0x44, 0x80, 0xec, 0xcd, 0x29, 0x16, 0x69, 0x1a, 0xd9, 0xd5, 0x97, 0xc1, 0x83, 0xa1, 0x10, 0xc3,
	0x11, 0xb5, 0x7a, 0x83, 0xc9, 0xc5, 0xc1, 0x6b, 0x19, 0x67, 0x19, 0x95, 0x8e, 0x16, 0xdc, 0x5f,
	0x96, 0x1b, 0x77, 0x12, 0x6d, 0xa5, 0x8f, 0xdf, 0x34, 0xc0, 0xeb, 0x72, 0x4d, 0x65, 0x9c, 0x18,
	0xef, 0xc8, 0x3d, 0xd8, 0xd4, 0x32, 0x4e, 0x68, 0xc4, 0x52, 0xbf, 0xd0, 0x28, 0xec, 0x6f, 0x85,
	0x1b, 0xb8, 0xee, 0xa6, 0xe4, 0x21, 0x78, 0x9a, 0x8d, 0x69, 0x24, 0x24, 0x1b, 0x32, 0xee, 0x17,
	0x1b, 0x85, 0xfd, 0x42, 0x08, 0x06, 0xfa, 0x1e, 0x11, 0xf2, 0x05, 0xdc, 0x55, 0x54, 0x5e, 0x51,
	0x19, 0x49, 0xfa, 0xaf, 0x09, 0x55, 0x3a, 0x52, 0x3a, 0x96, 0xda, 0x5f, 0x43, 0x26, 0xb1, 0xb2,
	0xd0, 0x8a, 0xfa, 0x46, 0x42, 0x5a, 0xb0, 0x3b, 0xd3, 0x50, 0x99, 0xe0, 0x8a, 0x3a, 0x95, 0x12,
	0xaa, 0xdc, 0x99, 0xaa, 0x58, 0x99, 0xd5, 0xb9, 0x80, 0x3b, 0x19, 0x95, 0x17, 0x42, 0x8e, 0x63,
	0x9e, 0xd0, 0x88, 0x72, 0x2d, 0x19, 0x55, 0x7e, 0xb9, 0xb1, 0xb6, 0xef, 0xb5, 0x7e, 0xdf, 0xbc,
	0x25, 0x4c, 0xcd, 0xdc, 0x21, 0x9b, 0xbd, 0xb9, 0x7e, 0x87, 0x6b, 0x79, 0x1d, 0x92, 0x6c, 0x11,
	0x61, 0x54, 0x91, 0xbf, 0x40, 0x59, 0x65, 0x31, 0x57, 0xfe, 0x3a, 0x5a, 0xfe, 0x74, 0x25, 0xcb,
	0xfd, 0x2c, 0xe6, 0xa1, 0xd5, 0x23, 0x7d, 0xa8, 0x8c, 0xd8, 0x40, 0xc6, 0xf2, 0x3a, 0x62, 0xfc,
	0x42, 0xf8, 0x1b, 0x8d, 0xc2, 0xbe, 0xd7, 0xfa, 0x62, 0x25, 0x3b, 0x27, 0x56, 0xb1, 0xcb, 0x2f,
	0x44, 0xe8, 0x8d, 0xe6, 0x0b, 0x63, 0xd4, 0x04, 0x85, 0x99, 0x0c, 0x19, 0xa3, 0x9b, 0xef, 0x60,
	0xb4, 0x6f, 0x15, 0xad, 0x51, 0x35, 0x5f, 0x90, 0x21, 0xec, 0x24, 0x23, 0x46, 0xb9, 0x8e, 0x62,
	0xad, 0x25, 0x1b, 0x4c, 0x34, 0x55, 0xfe, 0x16, 0x1e, 0xfb, 0x9b, 0x95, 0x2c, 0xb7, 0x51, 0xfb,
	0x70, 0xa6, 0x6c, 0xa3, 0x5a, 0x4f, 0x96, 0xe0, 0xe0, 0x7f, 0x1e, 0xd4, 0x97, 0x83, 0x4f, 0x3e,
	0x02, 0x30, 0x49, 0xbc, 0x8e, 0xf4, 0x75, 0x46, 0x5d, 0xd1, 0x6d, 0x21, 0x72, 0x76, 0x9d, 0x51,
	0x23, 0xc6, 0x9a, 0x88, 0x4c, 0xa5, 0xb9, 0xaa, 0xdb, 0x42, 0xe4, 0x8c, 0x8d, 0x29, 0x09, 0x60,
	0x33, 0x9d, 0x48, 0xbc, 0x5a, 0xae, 0xd0, 0x66, 0x6b, 0x42, 0xa0, 0xc4, 0xe3, 0x31, 0xc5, 0x6a,
	0xda, 0x0a, 0xf1, 0xdb, 0x60, 0xb8, 0x4f, 0xd9, 0x62, 0xe6, 0x9b, 0x7c, 0x0c, 0x55, 0xc6, 0x99,
	0x66, 0xb1, 0x16, 0xd2, 0x7a, 0xb1, 0x8e, 0xd2, 0xed, 0x19, 0x8a, 0x9e, 0x3c, 0x82, 0xca, 0x6b,
	0x21, 0x2f, 0xa9, 0x74, 0x45, 0xba, 0x81, 0xdb, 0x79, 0x16, 0xb3, 0xc5, 0xf9, 0x31, 0x54, 0x25,
	0x4d, 0x99, 0xa4, 0xc9, 0xb4, 0xf8, 0x37, 0x91, 0xb4, 0x3d, 0x45, 0xdf, 0xa6, 0x25, 0x62, 0xc2,
	0xb5, 0xbf, 0xd5, 0x28, 0xec, 0x97, 0xe7, 0xb4, 0xb6, 0x01, 0xcd, 0x86, 0x33, 0x1a, 0xe5, 0xa9,
	0x0f, 0x76, 0xc3, 0x29, 0xd6, 0xe1, 0x78, 0x29, 0x2f, 0xa8, 0x4e, 0x5e, 0xb9, 0xdd, 0x3c, 0x7b,
	0x29, 0x11, 0xb2, 0x5b, 0x35, 0xe1, 0x4e, 0x2a, 0xc6, 0x31, 0xe3, 0xd1, 0x48, 0x88, 0xcb, 0x49,
	0xe6, 0x88, 0x15, 0x24, 0xee, 0x58, 0xd1, 0x09, 0x4a, 0x2c, 0xff, 0x33, 0xd8, 0x59, 0xe4, 0x9b,
	0x8d, 0xb7, 0x91, 0x5d, 0xcb, 0xb3, 0xcd, 0xe6, 0xbf, 0x86, 0xed, 0x44, 0x70, 0x3e, 0x3f, 0x6c,
	0x15, 0x79, 0x15, 0x07, 0x5a, 0x83, 0x4f, 0x61, 0x4f, 0xd1, 0x64, 0x22, 0x69, 0xe4, 0x60, 0x26,
	0xb8, 0xa3, 0xd7, 0x90, 0xbe, 0x6b, 0xc5, 0xed, 0x99, 0xd4, 0xea, 0x3d, 0x04, 0x6f, 0x6a, 0xdc,
	0xb8, 0x50, 0xb7, 0x27, 0x73, 0x90, 0xd9, 0xfd, 0x33, 0xd8, 0xe1, 0xf4, 0x27, 0x1d, 0xbd, 0x12,
	0x59, 0x84, 0x95, 0x99, 0x88, 0x91, 0xbf, 0x83, 0x89, 0xab, 0x19, 0xc1, 0x73, 0x91, 0xf5, 0x1c,
	0x6c, 0x3c, 0x5d, 0xec, 0x49, 0xc4, 0x7a, 0x2a, 0xf3, 0xdd, 0x08, 0xb3, 0xb2, 0xd0, 0x86, 0xee,
	0x4c, 0x93, 0x97, 0x6f, 0x40, 0x98, 0x15, 0x47, 0x33, 0x9e, 0xdd, 0x9d, 0x66, 0xc5, 0x62, 0x2e,
	0x30, 0x5a, 0xc6, 0x5c, 0x5d, 0x98, 0x5a, 0x61, 0x3f, 0x53, 0x7f, 0xb7, 0x51, 0xd8, 0x5f, 0x0b,
	0x2b, 0x53, 0xb0, 0xcf, 0x7e, 0xa6, 0xc6, 0x7f, 0xca, 0x13, 0x91, 0xd2, 0x34, 0x1a, 0x88, 0xf4,
	0xda, 0x12, 0x3f, 0x40, 0x62, 0xcd, 0x09, 0x8e, 0x44, 0x7a, 0x3d, 0xe5, 0xa6, 0x74, 0x99, 0xbb,
	0x67, 0xb9, 0x4e, 0x30, 0xe3, 0x4a, 0xd8, 0x76, 0x4d, 0x55, 0xb3, 0x31, 0xe3, 0x43, 0xdf, 0xc7,
	0x9b, 0xfc, 0xdd, 0x7b, 0xb5, 0xc6, 0x3c, 0xd0, 0x47, 0xab, 0x67, 0x68, 0x34, 0xac, 0xa8, 0xdc,
	0x8a, 0xfc, 0x0e, 0xc8, 0x84, 0x8f, 0x44, 0x9c, 0x46, 0xf4, 0xca, 0xf4, 0x11, 0x1b, 0xbe, 0x7b,
	0x18, 0x99, 0xba, 0x95, 0x74, 0x8c, 0xc0, 0x46, 0x70, 0x1f, 0xea, 0x0b, 0x6c, 0x13, 0xc5, 0x00,
	0xb9, 0xd5, 0x1c, 0xd7, 0x04, 0xf2, 0x13, 0x30, 0x45, 0x17, 0xb1, 0xa9, 0x87, 0x57, 0xd4, 0xff,
	0xd0, 0x12, 0x53, 0x31, 0xee, 0xce, 0x51, 0x72, 0x04, 0x0f, 0x0c, 0x31, 0x11, 0x5c, 0x1b, 0x8b,
	0xc6, 0x08, 0x5d, 0x74, 0xe6, 0x3e, 0xea, 0x05, 0xa9, 0x18, 0xb7, 0x2d, 0xe9, 0x04, 0x39, 0x39,
	0xb7, 0xfe, 0x0c, 0xf7, 0x6f, 0xb5, 0x61, 0x5c, 0xfc, 0x08, 0x2d, 0xf8, 0x37, 0x5a, 0x30, 0xce,
	0x3e, 0x82, 0x8a, 0xd5, 0x1f, 0x67, 0x23, 0xaa, 0xa9, 0xff, 0xc0, 0x16, 0x06, 0xf2, 0x2d, 0x44,
	0x7e, 0x03, 0xd5, 0xa5, 0x73, 0x3f, 0xb4, 0x85, 0xb8, 0x70, 0xea, 0x7d, 0xa8, 0xbf, 0x15, 0xcb,
	0x86, 0x3d, 0xf6, 0x52, 0x24, 0x1f, 0x82, 0x31, 0x8f, 0xae, 0x9a, 0x4c, 0x3f, 0xb2, 0x97, 0x24,
	0x15, 0xe3, 0x13, 0x8b, 0x04, 0xff, 0x2e, 0xc0, 0xde, 0x2d, 0x29, 0x9c, 0xb5, 0xc7, 0x42, 0xae,
	0x3d, 0x36, 0xc0, 0x4b, 0xa9, 0x4a, 0x24, 0xcb, 0xb0, 0xa3, 0x16, 0x51, 0x94, 0x87, 0xc8, 0xd7,
	0x4b, 0x0d, 0xd7, 0x6b, 0xdd, 0x6f, 0xda, 0x11, 0xa3, 0x39, 0x1d, 0x31, 0x9a, 0xc7, 0x62, 0x32,
	0x18, 0xd1, 0xf3, 0x78, 0x34, 0xa1, 0xf3, 0x76, 0x1c, 0xfc, 0x77, 0x1b, 0x4a, 0xe6, 0x81, 0x24,
	0x7b, 0xb0, 0x61, 0x9e, 0xc8, 0xf9, 0x8c, 0xb1, 0x6e, 0x96, 0xdd, 0x94, 0xbc, 0x04, 0xc0, 0x69,
	0x43, 0xe9, 0x58, 0x9b, 0x5e, 0x6f, 0xea, 0xf6, 0x8f, 0x2b, 0x3f, 0xbc, 0xcd, 0xb3, 0x99, 0xae,
	0x7d, 0x80, 0x72, 0xc6, 0x4c, 0xe4, 0xb3, 0x58, 0x62, 0x3c, 0xdd, 0xd6, 0x6b, 0xb8, 0x75, 0xc5,
	0xa2, 0x7d, 0xeb, 0xc0, 0x4d, 0x2f, 0xc6, 0x33, 0x28, 0x5d, 0x32, 0x9e, 0xe2, 0x8b, 0x51, 0x6d,
	0xb5, 0x56, 0x77, 0xc7, 0xfc, 0xf3, 0x82, 0xf1, 0x34, 0x44, 0x7d, 0xd2, 0x82, 0xb2, 0x4d, 0xe5,
	0xfa, 0x0a, 0x51, 0xb3, 0x54, 0xd2, 0x84, 0x35, 0x53, 0x24, 0x1b, 0x2b, 0x68, 0x18, 0x22, 0xf9,
	0x03, 0x40, 0xee, 0x09, 0xb7, 0xc3, 0xc1, 0xde, 0x5b, 0x6a, 0x7d, 0x9c, 0x00, 0xc3, 0x1c, 0xd5,
	0x14, 0x92, 0xd2, 0x71, 0x72, 0x19, 0x61, 0xc8, 0xf0, 0x39, 0xda, 0x0a, 0x01, 0x21, 0x8c, 0x2a,
	0x39, 0x07, 0x2f, 0xe6, 0x5c, 0xd8, 0x21, 0x56, 0xf9, 0x80, 0xb9, 0xf9, 0x6a, 0xf5, 0x60, 0x1c,
	0xce, 0x94, 0xc3, 0xbc, 0x21, 0xf2, 0x4f, 0xa8, 0x8e, 0xa9, 0x52, 0xf1, 0x90, 0xda, 0x72, 0x57,
	0xbe, 0x87, 0xa6, 0x9f, 0xae, 0x6e, 0xfa, 0x3b, 0xab, 0x8f, 0xd7, 0x22, 0xdc, 0x1e, 0xe7, 0x56,
	0x8a, 0x1c, 0x43, 0x79, 0xc4, 0xf8, 0xa5, 0xf2, 0x2b, 0x68, 0xb5, 0xb9, 0xba, 0xd5, 0x13, 0xc6,
	0x2f, 0x43, 0xab, 0x4c, 0x9e, 0xc3, 0xba, 0xa9, 0xa2, 0x89, 0xc2, 0x97, 0x70, 0xe5, 0x79, 0x0b,
	0x8b, 0x00, 0xf5, 0x42, 0xa7, 0x4f, 0x7e, 0x84, 0x0f, 0x55, 0x3c, 0xa6, 0xe6, 0xc1, 0x4a, 0xa8,
	0x52, 0x51, 0xac, 0xa2, 0x5c, 0x59, 0xe2, 0x03, 0xea, 0xb5, 0x82, 0xb7, 0x32, 0x76, 0x24, 0xc4,
	0xc8, 0xa6, 0x79, 0xcf, 0xa8, 0xf7, 0xac, 0xf6, 0xa1, 0xea, 0xcd, 0x8a, 0x97, 0x3c, 0x83, 0x7a,
	0xf2, 0x8a, 0x8d, 0x52, 0x5b, 0xdf, 0x76, 0xaa, 0xa8, 0xdd, 0x52, 0x37, 0x3f, 0x74, 0xb9, 0x7e,
	0xd2, 0xb2, 0x06, 0xab, 0xa8, 0x65, 0x4c, 0xe0, 0xd0, 0x11, 0x7c, 0x0b, 0xb5, 0xa5, 0x7b, 0x44,
	0xea, 0xb0, 0x76, 0x49, 0xaf, 0xdd, 0x5d, 0x35, 0x9f, 0xe4, 0x2e, 0x94, 0xaf, 0x8c, 0xb6, 0x6b,
	0x10, 0x76, 0xf1, 0x4d, 0xf1, 0xeb, 0x42, 0xf0, 0x12, 0x60, 0x9e, 0x6a, 0x9c, 0xb6, 0x98, 0x6b,
	0x31, 0x85, 0x10, 0xbf, 0x97, 0x6a, 0xb4, 0xb8, 0x72, 0x8d, 0x06, 0xff, 0x29, 0x42, 0x25, 0x9f,
	0xeb, 0x1b, 0xad, 0x7f, 0xef, 0xe6, 0xbb, 0x22, 0xde, 0xd6, 0x3f, 0xbd, 0x5f, 0x15, 0x35, 0xcd,
	0xbc, 0xe7, 0x86, 0xc3, 0x2a, 0x14, 0x5d, 0xb3, 0x28, 0x85, 0x45, 0x96, 0x92, 0xdf, 0xc2, 0xce,
	0x84, 0x9b, 0x1e, 0x2f, 0xa9, 0x52, 0x34, 0xb5, 0x4f, 0x71, 0x09, 0xc5, 0xf5, 0xbc, 0x00, 0xdf,
	0xe2, 0x4f, 0xa0, 0xb6, 0x4c, 0x2d, 0x23, 0xb5, 0xba, 0x48, 0x7c, 0xfc, 0x15, 0x94, 0x70, 0xc6,
	0xbc, 0x0b, 0xf5, 0xb3, 0x97, 0xbd, 0x4e, 0xf4, 0xc3, 0x69, 0xbf, 0xd7, 0x69, 0x77, 0x9f, 0x75,
	0x3b, 0xc7, 0xf5, 0x5f, 0x91, 0x4d, 0x28, 0xf5, 0x3b, 0xa7, 0x67, 0xf5, 0x02, 0xa9, 0xc0, 0x66,
	0xd8, 0x69, 0x77, 0xba, 0xe7, 0x9d, 0xe3, 0x7a, 0x31, 0x78, 0x53, 0x84, 0x92, 0xa9, 0xd3, 0x5f,
	0xfa, 0xd9, 0x96, 0x6b, 0xb6, 0xc5, 0x85, 0x66, 0xfb, 0x37, 0x17, 0xa9, 0x35, 0x8c, 0xd4, 0x93,
	0x77, 0xbb, 0x19, 0xf9, 0x08, 0x2d, 0x26, 0xb4, 0xb4, 0x72, 0x42, 0x1f, 0x3f, 0x73, 0x87, 0xae,
	0x81, 0xb7, 0x78, 0xde, 0x5d, 0xd8, 0x69, 0x3f, 0xef, 0x9e, 0x1c, 0x47, 0x27, 0xdd, 0xd3, 0x17,
	0x9d, 0xe3, 0xa8, 0xdf, 0x3b, 0x3c, 0xad, 0x17, 0xc8, 0x07, 0x40, 0x7a, 0x87, 0x61, 0xe7, 0xf4,
	0x6c, 0x01, 0x2f, 0x06, 0x4f, 0x61, 0xdd, 0x5e, 0x33, 0x53, 0x11, 0x66, 0x18, 0xc2, 0x18, 0x94,
	0x43, 0xfc, 0x26, 0x3e, 0x6c, 0xb8, 0x9e, 0xe0, 0x02, 0x30, 0x5d, 0x3e, 0xfe, 0x16, 0x36, 0xa7,
	0x3d, 0x9a, 0xdc, 0x83, 0x5d, 0x63, 0x2d, 0x7a, 0xd1, 0x3d, 0x3d, 0x5e, 0x8a, 0x3e, 0xc0, 0x7a,
	0xbf, 0x13, 0x9e, 0x77, 0xc2, 0x7a, 0xc1, 0x7c, 0xb7, 0x4f, 0xba, 0x26, 0x17, 0xc5, 0x20, 0x06,
	0x2f, 0xf7, 0x3b, 0xcd, 0xe4, 0x7a, 0xfa, 0x7b, 0xef, 0x8a, 0x4a, 0x35, 0x7f, 0x3e, 0xab, 0x0e,
	0x3e, 0xb7, 0x28, 0xf9, 0x14, 0xea, 0xf4, 0xa7, 0x4c, 0x48, 0x4d, 0xe5, 0x8c, 0x69, 0x1f, 0xa3,
	0xda, 0x14, 0x77, 0xd4, 0xe0, 0x11, 0x78, 0xb9, 0x5f, 0x6d, 0x37, 0xbd, 0xd8, 0x41, 0x1b, 0x76,
	0x6f, 0xfc, 0xf9, 0xf5, 0x2e, 0xb7, 0xf6, 0x68, 0x08, 0x7b, 0x4c, 0xdc, 0x58, 0x01, 0x47, 0x9b,
	0x7f, 0xa7, 0x03, 0x9c, 0xa3, 0x7b, 0x85, 0x7f, 0xfc, 0xf5, 0x3d, 0xfe, 0xbc, 0x31, 0xa4, 0xfc,
	0xf3, 0xe1, 0xf4, 0x0f, 0x1a, 0x83, 0x75, 0x04, 0x9f, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xec,
	0x7d, 0x29, 0x83, 0x29, 0x11, 0x00, 0x00,
}
